### ISSUE TITLE
Help me with Execution

### ISSUE THREAD

**Issue by thulasis** [NathanWhelan/autormate-PAML-codeml#1]
Hi
Could you explain in brief how to execute this script. I provided alignment and tree file but still it was saying "IOError: The specified tree file does not exist."

**Comment by NathanWhelan** [comment]
I'm not sure without more information, but you may need to modify the shell script to make sure the naming convention for your tree file matches what is used in the Bash script.

**Comment by Naira-ipt** [comment]
@thulasis @NathanWhelan : You have to modify the tree file name
python codemlScript.py $NAME\_DNA.phy.aln $NAME\.phy.aln $NAME\_PAML_NeutralMethod1.out
